# Generated by Django 3.0 on 2019-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
