# Generated by Django 3.0 on 2019-12-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0003_auto_20191212_2255'),
        ('cars', '0002_car_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealership.DealerShip'),
        ),
    ]
