# Generated by Django 3.0 on 2019-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
