# Generated by Django 3.0 on 2019-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_auto_20191212_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='dealerships', to='dealership.Service'),
        ),
    ]
